name: Dependabot Auto Approve

on: 
  pull_request:
    branches:
      - master
  
jobs:
  auto_approve:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot-preview[bot]'
    steps:
      - uses: "hmarr/auto-approve-action@v1.0.0"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
